

#Nginx container
nginx:
  #The Dockerfile of our nginx is in "./nginx" folder
  build: ./mynginx

  #If the nginx container crash, we start it again
  restart: always

  #We specify that our nginx container depends on 3 nodes containers
  links:
    - node1:node1
    - node2:node2
    - node3:node3

  #We expose the port 80 of the container to the port 80 of or machine
  ports:
    - "80:80"

#Node (1) container
node1:

  #The Dockerfile of our node is in "./server" folder
  build: ./myplatform

  #If the node container crash, we start it again
  restart: always

  #We specify where the node container has to take his env variables



  #We expose the port 8080 of the container
  ports:
    - "8080"
#Node (2) container
node2:
  build: ./myplatform
  restart: always
  ports:
    - "8080"
#Node (3) container
node3:
  build: ./myplatform
  restart: always
  ports:
    - "8080"
#Mongo container
